languageCode: en-us
theme: codenamecore
params:
  copyright:
    start: 2021
    today: 2023
    rightholder: World of SteelCraft/Scary Master Playz
    notes: Elements of this website are owned by World of SteelCraft. Other third
      party copyrighted content are owned by their respective owners.
    managedByWhom: Currently managed by [dpG06](https://dplayzgames06.tk)
  cms:
    backend:
      name: github
      github:
        repo: worldofsteelcraft/web
        branch: main
        useGraphQL: true
        auth_endpoint: /api/auth
    logo_url: /images/logo.png
    media_folder: static/uploads
    public_folder: /uploads
    collections:
      - folder: content/announcements
        create: true
        label: Announcements
        name: announcements
        fieldType: defaultFields
      - folder: content/ban
        create: true
        label: Member Ban
        name: ban
        fieldType: defaultFields
      - folder: content/season-download
        create: true
        label: Season Download
        name: season-download
        fieldType: defaultFields
      - folder: content/knowledgebase
        create: true
        label: Knowledgebase
        name: knowledgebase
        fieldType: defaultFields
      - folder: content/rules
        create: false
        label: Rules
        name: rules
        fieldType: defaultFields
      - folder: content/blog
        create: true
        label: Blog
        name: blog
        fieldType: defaultFields
  theme:
    textColor:
      noDarkMode: true
    list:
      relatedArticle:
        enable: true
        articleSnippetStyle: listStyle
      sectionList:
        articleSnippetStyle: listStyle
    themeColor:
      light: "#32e532"
      dark: "#159d15"
    background:
      color:
        type: solid
        lightdarkscheme: true
        solid:
          light:
            color: "#32e532"
          dark:
            color: "#159d15"
        lineargradient:
          light:
            left:
              position: 10%
            right:
              position: 50%
          dark:
            left:
              position: 10%
            right:
              position: 50%
    pagePreviewImage: /images/preview.png
    linkcolor:
      main: lightblue
      visited: lightblue
    font:
      family: Roboto, Helvetica, Arial, sans-serif, Times New Roman
    iconFonts:
      fontawesome:
        enable: true
        type: cdnjs
        kits:
          kitName: d238301b93
        cdnjs:
          version: 6.4.2
  author: World of SteelCraft
  devBranchNotice:
    enable: true
    bugReportURL: https://github.com/dplayz/codenamecore
  comments:
    enable: true
    disqusShortName: worldofsteelcraft
  description: World of SteelCraft is a server owned by Scary Master Playz which
    is currently managed by himself and other admins. We're welcoming Filipino
    Minecraft Players to join
  identity:
    sdk:
      fbSDKID: 583745462831772
      onesignalSDKID: b1a79808-64a9-404e-9861-53a8ce9775c6
    webmaster:
      yandexValidationCode: d0d38a41ae470764
      noIndexAll: false
    analytics:
      googleAnalytics:
        measurementID: G-ZRTDYP4L7W
        disablePageView: false
    general:
      defaultAuthor:
        name: World of SteelCraft
      pagePreviewImage: /images/preview.png
      description: World of SteelCraft is a server owned by Scary Master Playz which
        is currently managed by himself and other admins. We're welcoming
        Filipino Minecraft Players to join
      logo: /images/logo.png
      favicon: favicon.ico
  psa:
    enable: true
    entries:
      - oneTime: true
        id: admin-notice-1
        content: Admins are currently busy with their lives right now, but services
          (SMP, Website) is still actively maintained. Check [Status
          Page](https://status.worldofsteelcraft.tk) for service status, and
          wait patiently when you message us.
        buttonText: Okay
        details: |
          Admins are currently busy with their lives right now, but services
          (SMP, Website) is still actively maintained. Check [Status
          Page](https://status.worldofsteelcraft.tk) for service status, and
          wait patiently when you message us.
  disableFeature:
    IEChecks: false
    googleTranslate: false
    widgetbotcrate: false
    onesignalSDK: false
    fbSDK: false
    twitterSDK: false
    googlePlatformSDK: false
enableRobotsTXT: false
buildDrafts: false
buildFuture: false
taxonomy:
  authors: author
outputs:
  home:
    - HTML
    - RSS
    - MANIFEST
    - CMSCONFIG
buildExpired: false
baseURL: https://worldofsteelcraft.tk/
title: World of SteelCraft
enableGitInfo: true
menu:
  main:
    - identifier: home
      name: Home
      params:
        url: /
        iconClass: fa-solid fa-home
      weight: 1
    - identifier: community-dropdown
      name: Community
      weight: 2
      params:
        url: /
        iconClass: fa-solid fa-users-line
    - identifier: banlist
      name: Banned Members
      parent: community-dropdown
      params:
        url: /ban
        iconClass: fa-solid fa-ban
      weight: 1
      
    - identifier: memberlist
      name: Member List
      parent: community-dropdown
      params:
        url: /member-list
        iconClass: fa-solid fa-table-list
      weight: 2
    - identifier: badgelist
      name: Badge
      parent: community-dropdown
      params:
        url: /badge
        iconClass: fa-solid fa-certificate
      weight: 3
    - identifier: Knowledgebase
      name: Knowledgebase
      parent: community-dropdown
      params:
        url: /knowledgebase
        iconClass: fa-solid fa-book
      weight: 4
    - identifier: rules-dropdown
      name: Rules
      weight: 3
      params:
        url: /
        iconClass: fa-solid fa-scale-balanced
    - identifier: rules-en
      name: English Rules
      parent: rules-dropdown
      params:
        url: /rules/en
        iconClass: fa-solid fa-scale-balanced
      weight: 1
    - identifier: rules-fil
      name: Filipino Rules
      parent: rules-dropdown
      params:
        url: /rules/fil
        iconClass: fa-solid fa-scale-balanced
      weight: 2
    - identifier: rules-en-basic
      name: Basic English Rules
      parent: rules-dropdown
      params:
        url: /rules/en-basic
        iconClass: fa-solid fa-scale-balanced
      weight: 3
    - identifier: rules-fil-basic
      name: Basic Filipino Rules
      parent: rules-dropdown
      params:
        url: /rules/fil-basic
        iconClass: fa-solid fa-scale-balanced
      weight: 4
    - identifier: server-dropdown
      name: Server
      weight: 4
      params:
        url: /
        iconClass: fa-solid fa-server
    - identifier: wosc-smp
      name: WoSC SMP
      parent: server-dropdown
      params:
        url: /server/smp
        iconClass: fa-solid fa-cube
      weight: 1
    - identifier: season-download
      name: Season Downloads
      parent: server-dropdown
      params:
        url: /season-download
        iconClass: fa-solid fa-download
      weight: 2
  footer:
    - identifier: community
      name: "Community:"
      params:
        iconClass: fa-solid fa-users-line
        links:
          - name: Member List
            url: /member-list
          - name: Community Member Badge
            url: /badge
          - name: Status Page
            url: https://status.worldofsteelcraft.tk
    - identifier: admin
      name: "Admin:"
      params:
        iconClass: fa-solid fa-user-gear
        links:
          - name: WoSC Data Sheet
            url: https://docs.google.com/spreadsheets/d/1B-b4DVKOoPPDkpAHgLbBY5y3GSPstsf9hvuSvLMR8xo/edit
          - name: Website Source Code
            url: https://github.com/worldofsteelcraft/web
          - name: Content Manager
            url: /admin
    - identifier: followUs
      name: "Follow us:"
      params:
        links:
          - name: Facebook Page
            url: https://facebook.com/worldofsteelcraft
          - name: Tiktok Account
            url: https://tiktok.com/@worldofsteelcraft
          - name: Youtube Channel
            url: https://youtube.com/@worldofsteelcraft
          - name: Twitter Account
            url: https://twitter.com/wosctwt
    - identifier: contact
      name: "Contact Us:"
      params:
        links:
          - name: Admin Mail
            url: mailto:admins@worldofsteelcraft.tk
          - name: Facebook Messenger
            links:
              - name: WoSC Messenger
                url: https://m.me/worldofsteelcraft
              - name: Scary Master Playz Messenger
                url: https://m.me/scarymasterFB
              - url: https://m.me/dplayzgames06
                name: dplayz Games Messenger
          - name: Discord Server
            url: https://discord.gg/DEMvpNuyXx
