baseURL: 'https://worldofsteelcraft.gq/'
languageCode: en-us
title: World of SteelCraft
theme: codenamecore
params:
  description: World of SteelCraft is a server owned by Scary Master Playz which is currently managed by himself and other admins. We're welcoming Filipino Minecraft Players to join
  pagePreviewImage: /images/preview.png
  author: World of SteelCraft
  devBranchNotice:
    enable: true
  sectionList: 
    articleSnippetStyle: listStyle
  relatedArticle: 
    enable: true
    articleSnippetStyle: listStyle
  copyrightyearStarted: 2021 
  copyrightyearToday: 2022
  copyrightHolder: World of SteelCraft/Scary Master Playz
  copyrightNotes: Elements of this website are owned by World of SteelCraft. Other third party copyrighted content are owned by their respective owners.
  managedByWhom: Currently managed by [dpG06](https://dplayzgames06.tk)
enableGitInfo: true
enableRobotsTXT: false
buildDrafts: false
buildFuture: false
buildExpired: false
disqusShortName: worldofsteelcraft
menu:
  main:
  - identifier: home
    name: Home
    params:
      url: /
    weight: 1
  - identifier: community-dropdown
    name: Community 
    weight: 2
  - identifier: banlist
    name: Banned Members
    parent: community-dropdown
    params:
      url: /ban
    weight: 1
  - identifier: memberlist
    name: Member List
    parent: community-dropdown
    params:
      url: /member-list
    weight: 2
  - identifier: badgelist
    name: Badge
    parent: community-dropdown
    params:
      url: /badge
    weight: 3
  - identifier: Knowledgebase
    name: Knowledgebase
    parent: community-dropdown
    params:
      url: /knowledgebase
    weight: 4
  - identifier: rules-dropdown
    name: Rules
    weight: 3
  - identifier: rules-en
    name: English Rules
    parent: rules-dropdown
    params:
      url: /rules/en
    weight: 1
  - identifier: rules-fil
    name: Filipino Rules
    parent: rules-dropdown
    params:
      url: /rules/fil
    weight: 2
  - identifier: rules-en-basic
    name: Basic English Rules
    parent: rules-dropdown
    params:
      url: /rules/en-basic
    weight: 3
  - identifier: rules-fil-basic
    name: Basic Filipino Rules
    parent: rules-dropdown
    params:
      url: /rules/fil-basic
    weight: 4
  - identifier: server-dropdown
    name: Server
    weight: 4
  - identifier: wosc-smp
    name: WoSC SMP
    parent: server-dropdown
    params:
      url: /server/smp
    weight: 1
  - identifier: season-download
    name: Season Downloads
    parent: server-dropdown
    params:
      url: /season-download
    weight: 2