baseURL: 'https://worldofsteelcraft.tk/'
languageCode: en-us
title: World of SteelCraft
theme: codenamecore
params:
  description: World of SteelCraft is a server owned by Scary Master Playz which is currently managed by himself and other admins. We're welcoming Filipino Minecraft Players to join
  author: World of SteelCraft
  theme: 
    background:
      color:
        type: solid
        lightdarkscheme: "true"
        light:
          color: "#32e532"
        dark: 
          color: "#159d15"
    pagePreviewImage: "/images/preview.png"
  identity:
    fbSDKID: 583745462831772
    onesignalSDKID: b1a79808-64a9-404e-9861-53a8ce9775c6
    yandexValidationCode: d0d38a41ae470764
    googleanalytics:
      measurementID: G-ZRTDYP4L7W
  devBranchNotice:
    enable: true
    bugReportURL: https://github.com/dplayz/codenamecore
  sectionList: 
    articleSnippetStyle: listStyle
  relatedArticle: 
    enable: true
    articleSnippetStyle: listStyle
  copyright:
    start: 2021
    today: 2022
    rightholder: "World of SteelCraft/Scary Master Playz"
    notes: Elements of this website are owned by World of SteelCraft. Other third party copyrighted content are owned by their respective owners.
    managedByWhom: "Currently managed by [dpG06](https://dplayzgames06.tk)"
enableGitInfo: true
enableRobotsTXT: false
buildDrafts: false
buildFuture: false
buildExpired: false
disqusShortName: worldofsteelcraft

taxonomy:
  authors: author
menu:
  main:
  - identifier: home
    name: Home
    params:
      url: /
    weight: 1
  - identifier: community-dropdown
    name: Community 
    weight: 2
  - identifier: banlist
    name: Banned Members
    parent: community-dropdown
    params:
      url: /ban
    weight: 1
  - identifier: memberlist
    name: Member List
    parent: community-dropdown
    params:
      url: /member-list
    weight: 2
  - identifier: badgelist
    name: Badge
    parent: community-dropdown
    params:
      url: /badge
    weight: 3
  - identifier: Knowledgebase
    name: Knowledgebase
    parent: community-dropdown
    params:
      url: /knowledgebase
    weight: 4
  - identifier: rules-dropdown
    name: Rules
    weight: 3
  - identifier: rules-en
    name: English Rules
    parent: rules-dropdown
    params:
      url: /rules/en
    weight: 1
  - identifier: rules-fil
    name: Filipino Rules
    parent: rules-dropdown
    params:
      url: /rules/fil
    weight: 2
  - identifier: rules-en-basic
    name: Basic English Rules
    parent: rules-dropdown
    params:
      url: /rules/en-basic
    weight: 3
  - identifier: rules-fil-basic
    name: Basic Filipino Rules
    parent: rules-dropdown
    params:
      url: /rules/fil-basic
    weight: 4
  - identifier: server-dropdown
    name: Server
    weight: 4
  - identifier: wosc-smp
    name: WoSC SMP
    parent: server-dropdown
    params:
      url: /server/smp
    weight: 1
  - identifier: season-download
    name: Season Downloads
    parent: server-dropdown
    params:
      url: /season-download
    weight: 2

outputs:
  home:
    - HTML
    - RSS
    - CMSCONFIG
params:
  cms:
    backend:
      name: git-gateway
      branch: main
    editorial_workflow: true
    media_folder: "static/uploads"
    public_folder: "uploads"
    display_url: "https://worldofsteelcraft.tk"
    logo_url: "/images/logo.png"
    collections: 
      - name: "blog"
        label: Blog
        folder: "content/blog"
        create: true
        slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
        fields: 
          - label: "Title"
            name: title
            type: "string"
          - label : "Publish Date"
            name: date
            type: datetime
            picker_utc: "false"
          - label: Body
            name: body
            type: markdown
          - label: "Custom Preview Image"
            name: customPagePreview
            type: "image"
            required: "false"
            default: "/images/preview.png"
          - label: "Exclude from Sitemap"
            name: sitemapExclude
            type: boolean
            required: "false"
            default: "true"
          - label: "Blog Author"
            name: author
            type: list
            required: "true"
          - label: "Hide from Public"
            name: featured
            type: "boolean"
            default: "true"
      - name: "season-download"
        label: "Season Download"
        folder: "content/season-download"
        create: true
        slug: "{{slug}}"
        fields: 
          - label: "Title"
            name: title
            type: "string"
          - label : "Publish Date"
            name: date
            type: datetime
            picker_utc: "false"
          - label: Body
            name: body
            type: markdown
          - label: "Description"
            name: "description"
            type: "string"
          - label: "Permalink"
            name: "permalink"
            type: "string"
          - label: "Custom Preview Image"
            name: customPagePreview
            type: "image"
            required: "false"
            default: "/images/preview.png"
          - label: "Exclude from Sitemap"
            name: sitemapExclude
            type: boolean
            required: "false"
            default: "true"
          - label: "Blog Author"
            name: author
            type: list
            required: "true"
      - name: "ban"
        label: "Ban"
        folder: "content/ban"
        create: true
        slug: "{{slug}}"
        fields: 
          - label: "Title"
            name: title
            type: "string"
          - label : "Publish Date"
            name: date
            type: datetime
            picker_utc: "false"
          - label: Body
            name: body
            type: markdown
          - label: "Description"
            name: "description"
            type: "string"
          - label: "Permalink"
            name: "permalink"
            type: "string"
          - label: "Custom Preview Image"
            name: customPagePreview
            type: "image"
            required: "false"
            default: "/images/preview.png"
          - label: "Exclude from Sitemap"
            name: sitemapExclude
            type: boolean
            required: "false"
            default: "true"
          - label: "Blog Author"
            name: author
            type: list
            required: "true"
      - name: "rules"
        label: "Rules"
        folder: "content/rules"
        create: false
        slug: "{{slug}}"
        fields: 
          - label: "Title"
            name: title
            type: "string"
          - label : "Publish Date"
            name: date
            type: datetime
            picker_utc: "false"
          - label: Body
            name: body
            type: markdown
          - label: "Description"
            name: "description"
            type: "string"
          - label: "Permalink"
            name: "permalink"
            type: "string"
          - label: "Custom Preview Image"
            name: customPagePreview
            type: "image"
            required: "false"
            default: "/images/preview.png"
          - label: "Exclude from Sitemap"
            name: sitemapExclude
            type: boolean
            required: "true"
            default: "true"
      - name: "knowledgebase"
        label: "Knowledgebase"
        folder: "content/knowledgebase"
        create: true
        slug: "{{slug}}"
        fields: 
          - label: "Title"
            name: title
            type: "string"
          - label : "Publish Date"
            name: date
            type: datetime
            picker_utc: "false"
          - label: Body
            name: body
            type: markdown
          - label: "Description"
            name: "description"
            type: "string"
          - label: "Permalink"
            name: "permalink"
            type: "string"
          - label: "Custom Preview Image"
            name: customPagePreview
            type: "image"
            required: "false"
            default: "/images/preview.png"
          - label: "Exclude from Sitemap"
            name: sitemapExclude
            type: boolean
            required: "false"
            default: "true"
          - label: "Blog Author"
            name: author
            type: list
            required: "true"
      - name: "donation-log"
        label: "Donation Log (WIP)"
        folder: "content/donation-log"
        create: false
        slug: "{{slug}}"
        fields: 
          - label: "Title"
            name: title
            type: "string"
          - label : "Publish Date"
            name: date
            type: datetime
            picker_utc: "false"
          - label: Body
            name: body
            type: markdown
          - label: "Description"
            name: "description"
            type: "string"
          - label: "Permalink"
            name: "permalink"
            type: "string"
          - label: "Custom Preview Image"
            name: customPagePreview
            type: "image"
            required: "false"
            default: "/images/preview.png"
          - label: "Blog Author"
            name: author
            type: list
            required: "true"
      - name: "announcement"
        label: "Announcements"
        folder: "content/announcements"
        create: true
        slug: "{{year}}-{{month}}-{{slug}}"
        fields: 
          - label: "Title"
            name: title
            type: "string"
          - label : "Publish Date"
            name: date
            type: datetime
            picker_utc: "false"
          - label: Body
            name: body
            type: markdown
          - label: "Permalink"
            name: "permalink"
            type: "string"
          - label: "Custom Preview Image"
            name: customPagePreview
            type: "image"
            required: "false"
            default: "/images/preview.png"
          - label: "Exclude from Sitemap"
            name: sitemapExclude
            type: boolean
            required: "false"
            default: "true"
          - label: "Blog Author"
            name: author
            type: list
            required: "true"
          - label: "Featured"
            name: featured
            type: "boolean"
            default: "true" 