# .github/workflows/preview.yml
name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: pr-${{ github.event.number }}

jobs:
  deploy-preview:
    permissions: write-all
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Submodules
        run:  git submodule update --init
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.101.0'
          extended: true
      - name: Build
        run: hugo --baseURL=https://worldofsteelcraft.github.io/web/pr-preview/pr-${{ github.event.number }}
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./public
          preview-branch: gh-pages
          umbrella-dir: pr-preview
